// Generated by CoffeeScript 1.4.0
(function() {
  var i, _i;

  document.write("Chunky Bacon");

  document.write("<h1> Chunky Bacon </h1>");

  for (i = _i = 10; _i >= 0; i = --_i) {
    document.write(i + "</br>");
  }

}).call(this);
