#!/usr/bin/env python
# -*- coding: CP1252 -*-
#
# generated by wxGlade 0.6.8 (standalone edition) on Wed Feb 05 20:20:04 2014
#


import time
from turtle import*
class Session(object):
    def __init__(self, start):
        self.start = start

    def startTimer(self, timelimit):
        n = timelimit
        #convert to miniutes
        m = n * 60
        #convert to seconds
        s = m * 60
        return s
    

    
    def newThread(self, name, description, timelimit):
        f = open("SessionID.txt","a")
        f.write("*********************" + '\n')
        f.write("Name: " + name + '\n')
        
        f.write("Description: " + description + '\n')
        
        f.write("Time: " + str(timelimit) + '\n')
        f.close()
       


import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.nameHere = wx.StaticText(self, wx.ID_ANY, _("Name:"))
        self.name = wx.TextCtrl(self, wx.ID_ANY, "")
        self.descriptionHere = wx.StaticText(self, wx.ID_ANY, _("Description:"))
        self.description = wx.TextCtrl(self, wx.ID_ANY, "")
        self.timeLimitHere = wx.StaticText(self, wx.ID_ANY, _("Time limit:"))
        self.timeLimit = wx.TextCtrl(self, wx.ID_ANY, "")
        self.button_click = wx.Button(self, wx.ID_ANY, _("Start"))
        self.labell = wx.Button(self, wx.ID_ANY, _(""))
        self.panel_output = wx.Panel(self, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.start, self.button_click)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(_("Remainder Notes v1.0"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.FlexGridSizer(4, 2, 1, 1)
        grid_sizer_1.Add(self.nameHere, 0, 0, 0)
        grid_sizer_1.Add(self.name, 0, 0, 0)
        grid_sizer_1.Add(self.descriptionHere, 0, 0, 0)
        grid_sizer_1.Add(self.description, 0, 0, 0)
        grid_sizer_1.Add(self.timeLimitHere, 0, 0, 0)
        grid_sizer_1.Add(self.timeLimit, 0, 0, 0)
        grid_sizer_1.Add(self.button_click, 0, 0, 0)
        grid_sizer_1.Add(self.labell, 0, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def start(self, event):  # wxGlade: MyFrame.<event_handler>
        name = self.name.Value
        description = self.description.Value
        timelimit = int(self.timeLimit.Value)
        go = Session("yes")
        go.newThread(name, description, timelimit)
        a = "Name: " + name + "\n" + "Description: " + description + "\n" + "Time limit: " + str(timelimit) + "\n"
        def countdown(timelimit):
            s = timelimit
            i = s
            while(i >= 0):
                self.labell.SetLabel(str(i))
                time.sleep(1)
                i = i - 1
        countdown(timelimit)
        
        event.Skip()

# end of class MyFrame
if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_3 = MyFrame(None, wx.ID_ANY, "")
    app.SetTopWindow(frame_3)
    frame_3.Show()
    app.MainLoop()
