#!/usr/bin/env python
# -*- coding: CP1252 -*-
#
# generated by wxGlade 0.6.8 (standalone edition) on Wed Aug 21 19:48:52 2013
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade
def check(input,key_1):
        x = len(input)

        a = key_1**2
        if x <= a:
            y = a - x
            for i in range(0,y):
                input = input + '_'

        return input 

def c_code(clear,key_2):
    output = ''
    b = key_2**2
    for i in range(0,(b-1)):
        for j in range(0,b,key_2):
                output = output + clear[j+i]

        if (j+i) == (b-1):
            break
    print len(output)
    return output

def c_code_2(clear,key_2):
    output = ''
    b = key_2**2
    for i in range(0,(b-1)):
        for j in range(0,b,key_2):
                output = output + clear[j+i]

        if (j+i) == (b-1):
            break
    chu = output.replace("~"," ")
    hjk = chu.replace("|","\n")
    nk = hjk.replace("_","")
    nk = nk.upper()
    return nk




def keyg(enter):
    n = len(enter)
    flag = 0
    for flag in range(0,100000):
        if flag >= n**0.5:
            break


    return  flag


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.label_1 = wx.StaticText(self, wx.ID_ANY, _("Enter the text to be scrambled or unscrambled.\n"))
        self.label_2 = wx.StaticText(self, wx.ID_ANY, _("Do you want to decode?\n\n\n"))
        self.radio_btn_1 = wx.RadioButton(self, wx.ID_ANY, _("If yes.\n\n\n\n"))
        self.text_ctrl_1 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.button_1 = wx.Button(self, wx.ID_ANY, _("Submit"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_RADIOBUTTON, self.yes_no, self.radio_btn_1)
        self.Bind(wx.EVT_BUTTON, self.submit, self.button_1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(_("Ceaser's Cipher."))
        self.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.label_1.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.label_2.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.radio_btn_1.SetBackgroundColour(wx.Colour(255, 255, 255))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.FlexGridSizer(3, 2, 0, 0)
        sizer_1.Add(self.label_1, 0, 0, 0)
        sizer_1.Add(self.label_2, 0, 0, 0)
        sizer_1.Add(self.radio_btn_1, 0, 0, 0)
        sizer_1.Add(self.text_ctrl_1, 0, wx.EXPAND | wx.ALIGN_RIGHT | wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL | wx.SHAPED | wx.FIXED_MINSIZE, 2)
        sizer_1.Add(self.button_1, 0, 0, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def yes_no(self, event):  # wxGlade: MyFrame.<event_handler>
        event.Skip()

    def submit(self, event):  # wxGlade: MyFrame.<event_handler>
        original = str(self.text_ctrl_1.Value)
        if original != '' :
            hj = original.lower()
            cpy = hj.replace(" ","~")
            copy = cpy.replace("\n","|")
            key = keyg(copy)
            ng = c_code(check(copy,key),key)
            self.button_1.SetLabel(ng)
        else:
            print "Try Again"
        event.Skip()

# end of class MyFrame
if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, wx.ID_ANY, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()

