# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48391b6b1081935710de44cb36edf0e5852bdadb6550a27aed3320547583911dbd8bccdb64672bef0fae340b1d00e11fb1f1655bf6c4c368a4a77e9dec3b6d83

test:
  secret_key_base: 6d4fa976a01348b7a8b96338bb46b4effbd7bc70dc291be55fa1952843d481aca056f988576d8adadb3a1be80af877e33db2727160026163e386f3dc2f0a4fe6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
